version: '3'

services:
  backend-service:
    build: ./be-app
    volumes:
      - ./be-app:/app
    ports:
      - 8080:8080
  
  frontend-service:
    build: ./fe-app
    volumes:
      - ./fe-app:/app


